### ISSUE TITLE
Virtuoso 7 dev fails to compile on ubuntu

### ISSUE THREAD

**Issue by H-B-Schmidt** [openlink/virtuoso-opensource#677]
Virtuoso : 7.2.5-dev
Ubuntu: 16.04.3 LTS

./autogen.sh
./configure
make

```
In file included from plugin_sample.c:24:0:

import_gate_virtuoso.h:361:12: error: unknown type name ‘typeof__sql_compile’
   struct { typeof__sql_compile *_ptr; const char *_name; } _sql_compile;

import_gate_virtuoso.h:363:12: error: unknown type name ‘typeof__sql_proc_to_recompile’
   struct { typeof__sql_proc_to_recompile *_ptr; const char *_name; } _sql_proc_to_recompile;

```

**Comment by HughWilliams** [comment]
Are you sure all the development software and tools required for the Linux build are in place as detailed at:

   http://vos.openlinksw.com/owiki/wiki/VOS/VOSMake#Requirements

I have been able to successfully build on Ubuntu 16.04 as have others ...

**Comment by idimopoulos** [comment]
Also, it might be a wrong comment, but if your openssl version is 1.1 then it is a bug already reported.
Best thing you can do is to use openssl 1.0.2 to build.

**Comment by H-B-Schmidt** [comment]
Thanks but I'm using openssl 1.0.2

Checking build environment ...
Using aclocal (GNU automake) 1.15
Using autoconf (GNU Autoconf) 2.69
Using autoheader (GNU Autoconf) 2.69
Using automake (GNU automake) 1.15
Using libtoolize (GNU libtool) 2.4.6
Using bison (GNU Bison) 3.0.4
Using flex 2.6.0
Using GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)
Using GNU gperf 3.0.4
Using OpenSSL 1.0.2g  1 Mar 2016

I just pulled the latest develop/7 from git and now even autogen.sh isn't working any longer :

Running autoconf ...

** ERROR **
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:1275: error: possibly undefined macro: AC_MSG_WARN

Bootstrap script aborting (see autogen.log for details) ...

with autogen.log showing :

configure.ac:331: error: possibly undefined macro: AC_PATH_PROG
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:1275: error: possibly undefined macro: AC_MSG_WARN

**Comment by idimopoulos** [comment]
ahh sorry! the openssl breaks the make. Ignore my last comment :)

**Comment by H-B-Schmidt** [comment]
Installing **pkg-config** solved both problems. Perhaps it should be mentioned as a build requirement ?

**Comment by openlink** [comment]
We are working on a fix so certain checks works on all platforms.
