### ISSUE TITLE
Cannot build with OpenSSL 3.0.x

### ISSUE THREAD

**Issue by jakubklimek** [openlink/virtuoso-opensource#1048]
_Originally posted by @pkleef in https://github.com/openlink/virtuoso-opensource/issues/663#issuecomment-1110870783:_

> @jakubklimek OpenSSL 3.0.x is now supported via commit 7d66d58e38145aafc2f0a47b996d6cfbf3a5728e
> 
> There is one testsuite item failing as it is using a very old encryption scheme that is not anymore supported on OpenSSL 3.0, but we are working on a fix. 
> 
> Other than that my testing on Ubuntu 22.04 LTS (Jammy Jellyfish) looks ok.
> 

@pkleef I get an error building VOS on Ubuntu 22.04 with just OpenSSL 3.0.x (stable/7):
```
/usr/include/openssl/dh.h:200:28: note: declared here
  200 | OSSL_DEPRECATEDIN_3_0 void DH_free(DH *dh);
      |                            ^~~~~~~
Dkernel.c: In function ‘ssl_server_init’:
Dkernel.c:5460:25: error: implicit declaration of function ‘OSSL_PROVIDER_load’ [-Werror=implicit-function-declar                                   ation]
 5460 |   ssl_legacy_provider = OSSL_PROVIDER_load(NULL, "legacy");
      |                         ^~~~~~~~~~~~~~~~~~
Dkernel.c:5460:23: warning: assignment to ‘OSSL_PROVIDER *’ {aka ‘struct ossl_provider_st *’} from ‘int’ makes po                                   inter from integer without a cast [-Wint-conversion]
 5460 |   ssl_legacy_provider = OSSL_PROVIDER_load(NULL, "legacy");
      |                       ^
Dkernel.c:5465:22: warning: assignment to ‘OSSL_PROVIDER *’ {aka ‘struct ossl_provider_st *’} from ‘int’ makes po                                   inter from integer without a cast [-Wint-conversion]
 5465 |   ssl_deflt_provider = OSSL_PROVIDER_load(NULL, "default");
      |                      ^
Dkernel.c:5468:6: error: implicit declaration of function ‘OSSL_PROVIDER_unload’ [-Werror=implicit-function-decla                                   ration]
 5468 |      OSSL_PROVIDER_unload(ssl_legacy_provider);
      |      ^~~~~~~~~~~~~~~~~~~~
Dkernel.c: In function ‘PEM_load_certs’:
Dkernel.c:5579:47: warning: unused parameter ‘pass’ [-Wunused-parameter]
 5579 | PEM_load_certs (const char *file, const char *pass)
      |                                   ~~~~~~~~~~~~^~~~
Dkernel.c: In function ‘PrpcFutureNextResult’:
Dkernel.c:4261:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
 4261 |         if (FUTURE_IS_NEXT_RESULT (future))
      |            ^
Dkernel.c:4271:7: note: here
 4271 |       case FS_FALSE:
      |       ^~~~
Dkernel.c: In function ‘PrpcFutureNextResult1T’:
Dkernel.c:4382:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
 4382 |       if (FUTURE_IS_NEXT_RESULT (future))
      |          ^
Dkernel.c:4392:5: note: here
 4392 |     case FS_FALSE:
      |     ^~~~
cc1: some warnings being treated as errors
make[2]: *** [Makefile:1269: libdksrv_la-Dkernel.lo] Error 1
make[2]: Leaving directory '/opt/virtuoso-opensource/libsrc/Dk'
make[1]: *** [Makefile:494: install-recursive] Error 1
make[1]: Leaving directory '/opt/virtuoso-opensource/libsrc'
make: *** [Makefile:685: install-recursive] Error 1

```

I did the build like so:
```
./autogen.sh
./configure --prefix=/usr/local/ --with-readline --program-transform-name="s/isql/isql-v/" --enable-fct-vad --enable-openssl
nice make
make install
```

And still, only manually adding `libssl1.0` and `libssl1.0-dev` (from an old Ubuntu or Debian repository) solves the issue.

**Comment by jakubklimek** [comment]
Also I am not sure if https://github.com/openlink/virtuoso-opensource/blob/develop/7/README.OpenSSL.md is still up to date with the update to OpenSSL 3.0.x

**Comment by pkleef** [comment]
Thanks for reporting. 

The fix has been committed to develop/7 branch
