### ISSUE TITLE
virtuoso 6.1.5 fails to build with bison 2.6

### ISSUE THREAD

**Issue by creffett** [openlink/virtuoso-opensource#9]
Compiling with bison 2.6 installed causes the build to fail, with the message:

In file included from sparql2sql.c:31:0:
sparql_p.h:451:5: error: conflicting types for ‘sparyyparse’
sparql.h:726:12: note: previous declaration of ‘sparyyparse’ was here

Full build logs are available at https://bugs.gentoo.org/show_bug.cgi?id=427674 if needed.

**Comment by creffett** [comment]
It appears that the issue is due to the following note from the ChangeLog for bison-2.6:
**\* Features deprecated since Bison 1.875
...
  YYPARSE_PARAM and YYLEX_PARAM, deprecated in favor of %parse-param and
  %lex-param, will no longer be supported.
...
Unfortunately, I don't understand Bison well enough to offer a patch for this change.

**Comment by openlink** [comment]
This has been fixed in the virtuoso opensource 6.1.6 version which has just been released.
