### ISSUE TITLE
Linking problem in Linux 64bit

### ISSUE THREAD

**Issue by tioannid** [openlink/virtuoso-opensource#800]
Hi, I am trying to evaluate the GeoSPARQL features of VSO and I had to clone the latest commit e6c411b6d7d0a88e4783913c1915bd2f39073d5f.
I followed the build instructions using the Linux 64-bit suggestion ( CFLAGS="-O2 -m64" ) and the standard recipe:
```
./autogen.sh
./configure
make
```
The following error is returned:
```
../../libsrc/Dk/.libs/libdksrv.a(libdksrv_la-Dkernel.o): In function `ssl_ctx_set_ecdh_curve':
Dkernel.c:(.text+0x6517): undefined reference to `OBJ_dn2nid'
collect2: error: ld returned 1 exit status
make[2]: *** [virtuoso-t] Error 1
```
The prerequisites (packages & versions) are in place (same or better) :
```
autoconf --version
automake --version
libtoolize --version
flex --version
bison --version
gperf --version
gawk --version
m4 --version
make --version
openssl version
```
Regards

**Comment by HughWilliams** [comment]
@tioannid What is the version of OpenSSL installed ? As note Virtuoso open source does not work with OpenSSL 1.1.x, and should be built with OpenSSL 1.0.x as has been recommended in other git issue reports where user have experienced issues building with OpenSSL 1.1.x ...

**Comment by tioannid** [comment]
Hi, my configuration follows:
```
$ uname -a && dpkg -l | grep openssl
Linux teleios4 3.13.0-137-generic #186-Ubuntu SMP Mon Dec 4 19:09:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
ii  libgnutls-openssl27:amd64                2.12.23-12ubuntu2.8                        amd64        GNU TLS library - OpenSSL wrapper
ii  openssl                                  1.0.1f-1ubuntu2.26                         amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  python-openssl                           0.13-2ubuntu6                              amd64        Python 2 wrapper around the OpenSSL library
```
I think this is an acceptable OpenSSL version and the CFLAGS values I used represent the platform I am using.
I will clone it again and rerun the process.

Thanks

**Comment by tioannid** [comment]
I am also sending the versions for all the prerequisite packages.
```

autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
automake (GNU automake) 1.14.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
libtoolize (GNU libtool) 2.4.2
Written by Gary V. Vaughan <gary@gnu.org>, 2003

Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
flex 2.5.35
bison (GNU Bison) 3.0.2
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
GNU gperf 3.0.4
Copyright (C) 1989-1998, 2000-2004, 2006-2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Douglas C. Schmidt and Bruno Haible.
GNU Awk 4.0.1
Copyright (C) 1989, 1991-2012 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.
m4 (GNU M4) 1.4.17
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Rene' Seindal.
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
OpenSSL 1.0.1f 6 Jan 2014

```

**Comment by tioannid** [comment]
After repeating the process this is the last page of the output which also contains the error:

```
viunix.c:283:1: warning: 'sigh_report_and_forget' defined but not used [-Wunused-function]
 sigh_report_and_forget (int sig)
 ^
  CCLD     libvirtuoso-t.la
  CC       virtuoso_t-viconfig.o
viconfig.c: In function ‘cfg_setup’:
viconfig.c:1088:3: warning: passing argument 4 of ‘cfg_getsize’ from incompatible pointer type [enabled by default]
   if (0 != cfg_getsize (pconfig, section, "HashJoinSpace", &chash_space_avail))
   ^
viconfig.c:680:5: note: expected ‘size_t *’ but argument is of type ‘long long int *’
 int cfg_getsize (PCONFIG pc, char * sec, char * attr, size_t * sz);
     ^
viconfig.c:1314:3: warning: passing argument 4 of ‘OPL_Cfg_getlong’ from incompatible pointer type [enabled by default]
   if (cfg_getlong (pconfig, section, "TimezonelessDatetimes", &c_timezoneless_datetimes) == -1)
   ^
In file included from ../../libsrc/libutil.h:33:0,
                 from viconfig.c:28:
../../libsrc/util/ncfg.h:111:21: note: expected ‘int *’ but argument is of type ‘long int *’
 #define cfg_getlong OPL_Cfg_getlong
                     ^
../../libsrc/util/ncfg.h:129:5: note: in expansion of macro ‘cfg_getlong’
 int cfg_getlong (PCONFIG pconfig, const char *section, const char *id, int32  *valptr);
     ^
  CC       virtuoso_t-viunix.o
viunix.c:298:1: warning: ‘sigh_set_notifiers’ defined but not used [-Wunused-function]
 sigh_set_notifiers ()
 ^
  CCLD     virtuoso-t
../../libsrc/Wi/.libs/libwi.a(libwi_la-bif_file.o): In function `bif_tmp_file':
bif_file.c:(.text+0x2371): warning: the use of `tempnam' is dangerous, better use `mkstemp'
../../libsrc/Dk/.libs/libdksrv.a(libdksrv_la-Dksesstr.o): In function `strdev_write':
Dksesstr.c:(.text+0x937): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
../../libsrc/Dk/.libs/libdksrv.a(libdksrv_la-Dkernel.o): In function `ssl_ctx_set_ecdh_curve':
Dkernel.c:(.text+0x6517): undefined reference to `OBJ_dn2nid'
collect2: error: ld returned 1 exit status
make[2]: *** [virtuoso-t] Error 1
make[2]: Leaving directory `/home/tioannidis/virtuoso-opensource/binsrc/virtuoso'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/tioannidis/virtuoso-opensource/binsrc'
make: *** [all-recursive] Error 1
```

Regards

**Comment by TallTed** [comment]
Hello, @tioannid -- 

I believe this is the first report of such an error when building with OpenSSL 1.0.1f. 

While we would generally expect things to build fine with that -- please note that until we have full support for OpenSSL 1.1, [we generally recommend using the latest Long Term Support (LTS) release of OpenSSL 1.0, which is now v1.0.2p](https://github.com/openlink/virtuoso-opensource/blob/develop/7/README.OpenSSL.md).

Are you able to update this and retry your build?

**Comment by tioannid** [comment]
Hi, @TallTed 
I will do this immediately.
Thanks

**Comment by tioannid** [comment]
Hi, @TallTed 
I downloaded the openssl-1.0.2p.tar.gz and make the build in ~/openssl-1.0.2p using the default build steps:
```
 $ ./config
  $ make
  $ make test
  $ make install
```
Do I need to change anything in the build process for virtuoso?

Regards

**Comment by tioannid** [comment]
Hi, @TallTed 
I tried repeating the build steps for virtuoso after building the openssl-1.0.2p but the following errors appeared:
```
viconfig.c:1088:3: warning: passing argument 4 of ‘cfg_getsize’ from incompatible pointer type [enabled by default]
   if (0 != cfg_getsize (pconfig, section, "HashJoinSpace", &chash_space_avail))
   ^
viconfig.c:680:5: note: expected ‘size_t *’ but argument is of type ‘long long int *’
 int cfg_getsize (PCONFIG pc, char * sec, char * attr, size_t * sz);
     ^
viconfig.c:1314:3: warning: passing argument 4 of ‘OPL_Cfg_getlong’ from incompatible pointer type [enabled by default]
   if (cfg_getlong (pconfig, section, "TimezonelessDatetimes", &c_timezoneless_datetimes) == -1)
   ^
In file included from ../../libsrc/libutil.h:33:0,
                 from viconfig.c:28:
../../libsrc/util/ncfg.h:111:21: note: expected ‘int *’ but argument is of type ‘long int *’
 #define cfg_getlong OPL_Cfg_getlong
                     ^
../../libsrc/util/ncfg.h:129:5: note: in expansion of macro ‘cfg_getlong’
 int cfg_getlong (PCONFIG pconfig, const char *section, const char *id, int32  *valptr);
     ^
  CC       virtuoso_t-viunix.o
viunix.c:298:1: warning: ‘sigh_set_notifiers’ defined but not used [-Wunused-function]
 sigh_set_notifiers ()
 ^
  CCLD     virtuoso-t
../../libsrc/Wi/.libs/libwi.a(libwi_la-bif_file.o): In function `bif_tmp_file':
bif_file.c:(.text+0x2371): warning: the use of `tempnam' is dangerous, better use `mkstemp'
../../libsrc/Dk/.libs/libdksrv.a(libdksrv_la-Dksesstr.o): In function `strdev_write':
Dksesstr.c:(.text+0x937): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
../../libsrc/Dk/.libs/libdksrv.a(libdksrv_la-Dkernel.o): In function `ssl_ctx_set_ecdh_curve':
Dkernel.c:(.text+0x6517): undefined reference to `OBJ_dn2nid'
collect2: error: ld returned 1 exit status
make[2]: *** [virtuoso-t] Error 1
make[2]: Leaving directory `/home/tioannidis/virtuoso-opensource/binsrc/virtuoso'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/tioannidis/virtuoso-opensource/binsrc'
make: *** [all-recursive] Error 1
```
Regards

**Comment by tioannid** [comment]
Hi, I reconfigured with the following:
`./configure --enable-openssl=/home/tioannidis/openssl-1.0.2p`
and now I got different errors:
```
/usr/include/geos/geom/Coordinate.h:60:16: note:   'geos::geom::Coordinate'
 class GEOS_DLL Coordinate {
                ^
./geos_export_from_virtgeo.cpp: In member function 'geos::geom::MultiPoint* geo_exporter_to_geos::export_MultiPoint(geo_t*)':
./geos_export_from_virtgeo.cpp:179:64: error: 'Coordinate' was not declared in this scope
         factory.createPoint (Coordinate (x, y, g->_.pline.Zs[i])) :
                                                                ^
./geos_export_from_virtgeo.cpp:179:64: note: suggested alternative:
In file included from /usr/include/geos/geom/Envelope.h:25:0,
                 from /usr/include/geos/geom/Geometry.h:27,
                 from /usr/include/geos/geom/GeometryFactory.h:23,
                 from ./geos_export_from_virtgeo.cpp:8:
/usr/include/geos/geom/Coordinate.h:60:16: note:   'geos::geom::Coordinate'
 class GEOS_DLL Coordinate {
                ^
./geos_export_from_virtgeo.cpp: In member function 'geos::geom::Point* geo_exporter_to_geos::export_Point(geo_t*)':
./geos_export_from_virtgeo.cpp:91:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[3]: *** [geos_la-geos_export_from_virtgeo.lo] Error 1
make[3]: Leaving directory `/home/tioannidis/virtuoso-opensource/binsrc/hosting/geos'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/tioannidis/virtuoso-opensource/binsrc/hosting'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/tioannidis/virtuoso-opensource/binsrc'
make: *** [all-recursive] Error 1

```
Regards

**Comment by TallTed** [comment]
Hi, @tioannid -- 

Was that the full `./configure` command you issued?

I wonder if you've read the [README.GeoSPARQL.md](https://github.com/openlink/virtuoso-opensource/blob/develop/7/README.GeoSPARQL.md), and pre-built those specific versions of `proj` and `geo` libraries?  (Unlike the libraries required for the main build, these features require the specific listed versions.)

**Comment by tioannid** [comment]
Thanks @TallTed 
I will do so right now.
Regards

**Comment by tioannid** [comment]
Hi, @TallTed 
I downloaded and built the versions required (openssl, geos, proj) in the directories displayed and used the following recipe for building virtuoso:
```
CFLAGS="-O2 -m64"
export CFLAGS
./autogen.sh
./configure -enable-proj4=/home/tioannid/Downloads/proj-4.9.3 --enable-geos=/home/tioannid/Downloads/geos-3.5.1 --enable-openssl=/home/tioannid/Downloads/openssl-1.0.2p
 make
```
I don't think I missed something else. The shapefileio plugin is embedded in the Virtuoso code base. Still I am getting the following error:

```
./geos_plugin.cpp: In function ‘char* bif_geos_s_g2g_combination(char**, char**, state_slot_t**, Geometry_g2g_combination_membptr_t, const char*)’:
./geos_plugin.cpp:1177:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<geos::geom::Geometry> arg1 (export_geo_as_Geometry (raw_arg1));
        ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./geos_plugin.cpp:28:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
./geos_plugin.cpp:1178:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<geos::geom::Geometry> arg2 (export_geo_as_Geometry (raw_arg2));
        ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./geos_plugin.cpp:28:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
./geos_plugin.cpp:1179:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<geos::geom::Geometry> res;
        ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./geos_plugin.cpp:28:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
./geos_plugin.cpp:1180:20: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   try { res = std::auto_ptr<geos::geom::Geometry> (((arg1.get())->*op_membptr)(arg2.get())); }
                    ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from ./geos_plugin.cpp:28:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
Makefile:642: recipe for target 'geos_la-geos_plugin.lo' failed
make[3]: *** [geos_la-geos_plugin.lo] Error 1
make[3]: Leaving directory '/home/tioannid/NetBeansProjects/PhD/virtuoso-opensource/binsrc/hosting/geos'
Makefile:494: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/tioannid/NetBeansProjects/PhD/virtuoso-opensource/binsrc/hosting'
Makefile:488: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tioannid/NetBeansProjects/PhD/virtuoso-opensource/binsrc'
Makefile:683: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```
Regards

**Comment by TallTed** [comment]
Hi, @tioannid --

We've applied [a few more commits](https://github.com/openlink/virtuoso-opensource/commits/develop/7) to the `develop/7` branch since your clone, which resolve at least a couple of the build issues you've hit (and worked past).  I am wondering whether these will also resolve the latest build issue you've hit as well.

Can you update your branch, and try one more rebuild?

**Comment by tioannid** [comment]
Hi, @TallTed 
I will do so now. But for completeness shake I would like to mention that the initial commit I got, I tried to deploy to 4 different servers. With your comments I managed to successfully deploy VSO to an Ubuntu 14.04.5 LTS and an Ubuntu 12.04.5 LTS, which are actually the final target machines where my tests have to run. But I failed to do the same on 2 development VM that I have, an Ubuntu 18.04.1 LTS and a Debian 9.
I will be back with comments on my attempts.
Thanks

**Comment by tioannid** [comment]
Hi, @TallTed 
It worked the first time! Connecting with isql and web ui.
Regards

**Comment by TallTed** [comment]
Hi, @tioannid -- Great!  If I understand correctly, we can mark this issue closed, and consider `develop/7` as of 2018-11-12 to have been tested build-compatible with all of Ubuntu 18.04.1 LTS, Ubuntu 14.04.5 LTS, Ubuntu 12.04.5 LTS, and Debian 9.  Would you concur?

**Comment by tioannid** [comment]
Hi, @TallTed 
I will try to build it in my Debian 9 machine and verify whether all 4 cases have been tested.
I will be back in an hour.
Regards

**Comment by tioannid** [comment]
Hi, @TallTed 
I confirm that the latest commit installed according to the instructions in a Debian 9.6 (strech) linux as well.
Bye.

**Comment by TallTed** [comment]
Great!  Thanks, @tioannid.  I'll close this issue now.
