### ISSUE TITLE
Compile error of latest git checkout

### ISSUE THREAD

**Issue by H-B-Schmidt** [openlink/virtuoso-opensource#712]
The latest git checkout no longer does compile with Ubuntu 16.04 LTS :

```

sqlcomp2.c:1603:8: note: each undeclared identifier is reported only once for each function it appears in
sqlcomp2.c:1603:25: error: ‘save_tlsf’ undeclared (first use in this function)
        self->thr_tlsf = save_tlsf;

```

**Comment by timhaynesopenlink** [comment]
Hi,

Confirmed; replicated in-house on two distros. We'll see what we can do.

Thanks,

~Tim

**Comment by openlink** [comment]
A fix has been pushed
